FROM maven:3-amazoncorretto-21 AS build

WORKDIR /app
COPY ./src ./src
COPY ./pom.xml ./pom.xml
RUN mvn package

FROM alpine:3 AS final

RUN apk add openjdk21-jre

COPY --from=build --chown=185 /app/target/quarkus-app/lib/ /deployments/lib/
COPY --from=build --chown=185 /app/target/quarkus-app/*.jar /deployments/application.jar
COPY --from=build --chown=185 /app/target/quarkus-app/app/ /deployments/app/
COPY --from=build --chown=185 /app/target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
CMD ["java", "-jar", "/deployments/application.jar"]
